#pragma once
#include <stdbool.h>
#include <stdint.h>
#define TESTS_STRUCTS_FLAT_ARRAY_1 (10)
#define TESTS_STRUCTS_FLAT_ARRAY_2 (20)
#define TESTS_STRUCTS_FLAT_ARRAY_3 (30)
#define TESTS_STRUCTS_FLAT_ARRAY_4 (40)
#define TESTS_STRUCTS_FLAT_STRUCTURE_FIELD1 (42)
#define TESTS_STRUCTS_FLAT_STRUCTURE_FIELD2 ("fourty two")
#define TESTS_STRUCTS_FLAT_STRUCTURE_FIELD3 (true)
#define TESTS_STRUCTS_FLAT_STRUCTURE_FIELD4 (3.1415926535898)
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_01 (42)
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_02_X (0)
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_02_Y (1)
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_03_A ("hi")
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_03_B (true)
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_04_1 ("one")
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_04_2 ("two")
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_04_3 ("three")
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_05_1_1 (1)
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_05_1_2 (2)
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_05_2_1 (3)
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_05_2_2 (4)
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_05_3_1 (5)
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_05_3_2 (6)
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_1_1_1_ST_A (1)
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_1_1_1_ST_B (2)
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_1_1_1_X (1)
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_1_1_1_Y ("one")
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_1_1_2_X (2)
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_1_1_2_Y ("two")
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_1_2_1_X (-1)
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_1_2_2_Y ("N/A")
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_1_3_1_ST_A (3)
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_1_3_1_ST_B (4)
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_1_3_1_Z (0.1)
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_1_3_2_Z (0.2)
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_2_1_1_ARR_1 ("a")
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_2_1_1_ARR_2 ("b")
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_2_1_1_X (10)
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_2_1_1_Y ("ten")
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_2_1_2_X (20)
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_2_1_2_Y ("twenty")
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_2_2_1_X (-2)
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_2_2_2_Y ("N/A")
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_2_3_1_ARR_1 ("cd")
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_2_3_1_ARR_2 ("efg")
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_2_3_1_Z (3.1415926535898)
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_2_3_2_Z (1.5707963267949)
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_3_1_1_S ("")
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_3_1_1_S2 ("---------------------------------------")
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_4_1_1_T (true)
#define TESTS_STRUCTS_SAME_NAME ("global")
#define TESTS_STRUCTS_TABLE_SAME_NAME ("field")
struct t_tests_structs
{
#define TESTS_STRUCTS_FLAT_ARRAY_SIZE1 4
    uint8_t flat_array[TESTS_STRUCTS_FLAT_ARRAY_SIZE1];
    struct t_tests_structs_flat_structure
    {
        uint8_t field1;
#define TESTS_STRUCTS_FLAT_STRUCTURE_FIELD2_LEN 11
        char field2[TESTS_STRUCTS_FLAT_STRUCTURE_FIELD2_LEN];
        bool field3;
        double field4;
    } flat_structure;
    struct t_tests_structs_mega_struct
    {
        uint8_t field_01;
        struct t_tests_structs_mega_struct_field_02
        {
            uint8_t x;
            uint8_t y;
        } field_02;
        struct t_tests_structs_mega_struct_field_03
        {
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_03_A_LEN 3
            char a[TESTS_STRUCTS_MEGA_STRUCT_FIELD_03_A_LEN];
            bool b;
        } field_03;
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_04_SIZE1 3
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_04_LEN 6
        char field_04[TESTS_STRUCTS_MEGA_STRUCT_FIELD_04_SIZE1][TESTS_STRUCTS_MEGA_STRUCT_FIELD_04_LEN];
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_05_SIZE1 3
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_05_SIZE2 2
        uint8_t field_05[TESTS_STRUCTS_MEGA_STRUCT_FIELD_05_SIZE1][TESTS_STRUCTS_MEGA_STRUCT_FIELD_05_SIZE2];
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_SIZE1 4
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_SIZE2 3
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_SIZE3 2
        struct t_tests_structs_mega_struct_field_06
        {
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_ARR_SIZE1 2
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_ARR_LEN 4
            char arr[TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_ARR_SIZE1][TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_ARR_LEN];
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_S_LEN 1
            char s[TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_S_LEN];
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_S2_LEN 40
            char s2[TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_S2_LEN];
            struct t_tests_structs_mega_struct_field_06_st
            {
                uint8_t a;
                uint8_t b;
            } st;
            bool t;
            int8_t x;
#define TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_Y_LEN 7
            char y[TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_Y_LEN];
            double z;
        } field_06[TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_SIZE1][TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_SIZE2]
                  [TESTS_STRUCTS_MEGA_STRUCT_FIELD_06_SIZE3];
    } mega_struct;
#define TESTS_STRUCTS_SAME_NAME_LEN 7
    char same_name[TESTS_STRUCTS_SAME_NAME_LEN];
    struct t_tests_structs_table
    {
#define TESTS_STRUCTS_TABLE_SAME_NAME_LEN 6
        char same_name[TESTS_STRUCTS_TABLE_SAME_NAME_LEN];
    } table;
};
extern const struct t_tests_structs TESTS_STRUCTS;
